[assembly:System.Reflection.AssemblyTitle("ReadLine")]
[assembly:System.Reflection.AssemblyDescription("A GNU-Readline like library for .NET/.NET Core")]
[assembly:System.Reflection.AssemblyFileVersion("1.2.1")]
[assembly:System.Reflection.AssemblyVersion("1.2.1")]
[assembly:System.Reflection.AssemblyInformationalVersion("1.2.1")]