[assembly:System.Reflection.AssemblyTitleAttribute("ReadLine")]
[assembly:System.Reflection.AssemblyDescriptionAttribute("A GNU-Readline like library for .NET/.NET Core")]
[assembly:System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]
[assembly:System.Reflection.AssemblyVersionAttribute("1.0.0.0")]
[assembly:System.Reflection.AssemblyInformationalVersionAttribute("1.0.0")]
[assembly:System.Runtime.CompilerServices.InternalsVisibleTo("ReadLine.Tests")]